language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - cpanm JSON::Parse
  - cpanm C::Tokenize
  - cp lib/JSON/Repair.pod.tmpl lib/JSON/Repair.pod   
  - perl Makefile.PL
  - make test  
